# Source files:
# Manually listed to allow fine control of what files get compiled.
define src =
Util/Directory.cpp \
Grid.cpp \
main.cpp \
Program_Factory.cpp \
Program.cpp \
Sector.cpp
endef
src := $(addprefix src/Nightfall/, $(src))

# Release version object files:
rls_obj = $(src:.cpp=.o)
rls_obj := $(subst src/, obj/, $(rls_obj))

# Debug version object files:
dbg_obj = $(src:.cpp=-dbg.o)
dbg_obj := $(subst src/Nightfall/, obj/Nightfall-dbg/, $(dbg_obj))

# Makefiles:
make = $(src:.cpp=.mk)
make := $(subst src/, make/, $(make))

# Statically links in the SFML library.
lSFML = -DSFML_STATIC -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32

# Defines standard directories for headers and libraries, as well as C++ standard.
misc = -I'include/' -L'lib/' -std=c++17

cxxflags = $(misc) -lLog $(lSFML)

r: release
rls: release
release: Nightfall.exe
d: debug
dbg: debug
debug: Nightfall-dbg.exe

include $(make)

# Generates release version executable.
Nightfall.exe: $(rls_obj)
	g++ -O3 $^ -o $@ $(cxxflags)

# Generates debug version executable.
Nightfall-dbg.exe: $(dbg_obj)
	g++ -g -O0 $^ -o $@ $(cxxflags)

# Generates release object files.
obj/Nightfall/%.o: src/Nightfall/%.cpp
	@mkdir -p $(dir $@)
	g++ -O3 -c $< -o $@ $(cxxflags)

# Generates debug object files.
obj/Nightfall-dbg/%-dbg.o: src/Nightfall/%.cpp
	@mkdir -p $(dir $@)
	g++ -g -O0 -c $< -o $@ $(cxxflags)

# Automatically generates pre-requisite makefile (.mk) for each object file using g++.
# Then, sed is used to make the release object file, debug object file, and the 
# 	makefile itself targets of the recipe.
# Including the created makefile as a target of the recipe contained within itself 
#	ensures that it will be updated along with any changes to the pre-requisites 
#	of the associated object file.
make/Nightfall/%.mk: src/Nightfall/%.cpp
	@mkdir -p $(dir $@)
	@set -e; rm -f $@; \
	g++ -MM $(misc) $< > $@.temp; \
	sed 's,$(subst .mk,.o,$(notdir $@)),$(subst make/,obj/,$(subst .mk,.o,$@)) $(subst make/Nightfall/,obj/Nightfall-dbg/,$(subst .mk,-dbg.o,$@)) $@,g' < $@.temp > $@; \
	rm -f $@.temp

# Deletes any and all files that are automatically generated by this Makefile.
clean:
	rm -f Nightfall.exe
	rm -f Nightfall-dbg.exe
	rm -f -r obj/**
	rm -f -r make/**